### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Ctrl-Vinayak** [NareshJaipal/Other_Projects#1]
.

**Comment by Crtl-Vinayak** [comment]
I see you have 6 subprojects in this flutter project.
When you make the calculator app, I will make a demo of a todo app.

**Comment by Codewith-ARK** [comment]
Hey Vinayak 👋🏻

Do you want to collaborate on any web (HTML, CSS, JS, React) projects?

**Comment by Codewith-ARK** [comment]
> I see you have 6 subprojects in this flutter project. When you make the calculator app, I will make a demo of a todo app.

Hey Vinayak 👋🏻

Do you want to collaborate on any Web (HTML, CSS, JS, React, Node.js) projects?

**Comment by Crtl-Vinayak** [comment]
> > I see you have 6 subprojects in this flutter project. When you make the calculator app, I will make a demo of a todo app.
> 
> Hey Vinayak 👋🏻
> 
> Do you want to collaborate on any Web (HTML, CSS, JS, React, Node.js) projects?

At the moment, I am focusing on this flutter project.
So I can't collaborate with you.
It will be a bit too much for me if I work now with another project.
Although thanks for inviting me to collaborate with you.

**Comment by Codewith-ARK** [comment]
> > > I see you have 6 subprojects in this flutter project. When you make the calculator app, I will make a demo of a todo app.
> > 
> > 
> > Hey Vinayak 👋🏻
> > Do you want to collaborate on any Web (HTML, CSS, JS, React, Node.js) projects?
> 
> At the moment, I am focusing on this flutter project. So I can't collaborate with you. It will be a bit too much for me if I work now with another project. Although thanks for inviting me to collaborate with you.

Alright, no problem Vinayak. Hit me up whenever you're ready for collaboration on a web-app.

**Comment by NareshJaipal** [comment]
Ya sure, lets chat about it over whatsapp

**Comment by Crtl-Vinayak** [comment]
> Ya sure, lets chat about it over whatsapp

Note, I don't think I'm going to be able to make a flutter todo app within this month, let alone to make a simple flutter app. The reason is not that flutter is hard to start programming, but that I am doing many studies at the same time, which makes this hard to start working and focusing to program.

If I really have time, I will try to work on this project. In advance, sorry that this message arrived a bit late. I generally don't work very fast and I don't work very much with deadlines, so I spend more time on other things in my free time.

What might be helpful for this project, is for @NareshJaipal or @Codewith-ARK to create a project for this repository, so we can see what parts and subparts need to be done and what needs to be fixed. This helps to see what small parts of the project can be made quickly or need more time to consider/evaluate how to build a massive certain app.

Lastly, I don't use Whatsapp, discord, or other social media, due to privacy reasons. We may be able to use Signal to communicate. https://signal.org/

This is my current situation what I am in.

**Comment by Crtl-Vinayak** [comment]
Also, if you guys have some flutter documents that I can use to understand the basics of flutter, can you guys send it here in the comments of this issue, that will help me a lot. I really dislike the tutorial hell of YouTube. I really dont want to sit on hours to watch tutorials on YouTube. Documents with theory and examples and previews of how the app(s) looks like is a really big win for me.

**Comment by Crtl-Vinayak** [comment]
@NareshJaipal can you delete this issue.

**Comment by Ctrl-Vinayak** [comment]
Sorry to interrupt you, but can you delete this issue.
